# add ~/.bin to path
[[ -d $HOME/.bin ]] && \
    export PATH="$HOME/.bin:$PATH"

# history config
HISTCONTROL=ignoreboth  # ignore duplicate history & indentation
shopt -s histappend     # append to history file, dont overwrite
HISTSIZE=1000
HISTFILESIZE=2000

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# add newline after every command, except clear
PROMPT_COMMAND="export PROMPT_COMMAND=echo"
alias clear='PROMPT_COMMAND="export PROMPT_COMMAND=echo"; clear'

# aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias py=python3

# fun script kiddie stuff
hack() {
    tput civis
    stty_orig=`stty -g`
    stty -echo
    timeout 1 tree /
    timeout 1 ls -R /
    sleep 0.5
    hexdump /bin/bash
    clear
    timeout 1 traceroute google.com
    clear
    timeout 1 traceroute bing.com
    clear
    timeout 1 logs 1
    timeout 0.5 logs 20
    timeout 1.5 logs
    echo
    sleep 0.5
    printf "[COMPLETE]"
    sleep 1
    printf " Access Granted."
    sleep 1
    echo
    echo
    stty $stty_orig
    tput cnorm
}

inject() {
    # timeout 1 logs 5
    # clear
    echo
    printf "INITIALIZING"
    sleep 0.25
    for i in $(seq 3); do
        printf "."
        sleep 0.25
    done
    printf "\rINITIALIZING   "
    printf "\rINITIALIZING"
    sleep 0.25
    printf "."
    sleep 0.2
    echo ".. DONE"
    tput civis
    stty_orig=`stty -g`
    stty -echo
    for file in /bin/*; do
        wc $file
        sleep 0.01
    done
    echo
    echo "BOOTLOADER INJECTED"
    stty $stty_orig
    tput cnorm
}

override() {
    tput civis
    stty_orig=`stty -g`
    stty -echo
    timeout 1 traceroute google.com
    clear
    timeout 1 traceroute bing.com
    clear
    top
    stty $stty_orig
    tput cnorm
}

hidetrace() {
    sleep 3
}

bootload() {
    tput civis
    stty_orig=`stty -g`
    stty -echo
    timeout 1 tree /
    timeout 1 ls -R /
    sleep 0.5
    hexdump /bin/bash
    clear
    timeout 1 logs 1
    timeout 0.5 logs 20
    timeout 1.5 logs
    echo
    sleep 0.5
    printf "[COMPLETE]"
    sleep 1
    printf " Data extracted."
    sleep 1
    echo
    echo
    stty $stty_orig
    tput cnorm
}
